### ISSUE TITLE
Не получает позывной с QSO.su

### ISSUE THREAD

**Issue by EzikMarconi** [qsosu/logger#9]
Только собрал. 
Запустил, ввел ключ. 
Перешел в управление позывными, нажал "обновить с QSO.SU". 
Появилось сообщение что позывной отсутствует, добавляем. 
Позывного нет.

![image](https://github.com/user-attachments/assets/b20ecce0-cbd0-42aa-a430-81ce942fc5ea)

**Comment by c7v** [comment]
Привет! Спасибо за отчёт!

Попробуй сейчас с нуля с ветки master скомпилить ещё раз. Там баг на сколько я понимаю, из-за базы данных.

**Comment by EzikMarconi** [comment]
обновление и полная пересборка помогла.
Спасибо

**Comment by c7v** [comment]
Исправлена ошибка 99. [1.2.362](https://github.com/qsosu/logger/releases/tag/1.2.362)
